# Generated by Django 4.2.20 on 2025-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_project_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
