# Generated by Django 4.2.20 on 2025-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
